KERNEL_VERSION="3.7.6"
LOCAL_VERSION="-pf"

post_install () {
  echo ">>> Updating module dependencies..."
  /sbin/depmod -A -v ${KERNEL_VERSION}${LOCAL_VERSION}
  echo ">>> Creating initial ramdisk..."
  mkinitcpio -p linux37-pf
}

post_upgrade() {
  echo ">>> Updating module dependencies..."
  /sbin/depmod -A -v ${KERNEL_VERSION}${LOCAL_VERSION}
  echo ">>> Creating initial ramdisk..."
  mkinitcpio -p linux37-pf
}

